import type { School } from "./types"

export const mockSchools: School[] = [
  {
    id: "1",
    name: "Auto Escola Brasília",
    address: "Rua Principal, 123 - Samambaia Norte, Brasília - DF",
    distance: "3.9km",
    rating: 3.7,
    maxRating: 5,
    type: "Credenciada",
    categories: ["A", "B", "AB"],
  },
  {
    id: "2",
    name: "Centro de Formação de Condutores DF",
    address: "Av. Central, 456 - Taguatinga, Brasília - DF",
    distance: "2.6km",
    rating: 4.2,
    maxRating: 5,
    type: "Credenciada",
    categories: ["B", "AB"],
  },
  {
    id: "3",
    name: "CFC Cidade Brasília",
    address: "Rua Comercial, 789 - Asa Sul, Brasília - DF",
    distance: "4.6km",
    rating: 5,
    maxRating: 5,
    type: "Parceira",
    categories: ["A", "B", "AB"],
  },
  {
    id: "4",
    name: "Auto Escola Piloto",
    address: "Quadra 101, Lote 5 - Águas Claras, Brasília - DF",
    distance: "1.5km",
    rating: 4.8,
    maxRating: 5,
    type: "Credenciada",
    categories: ["A", "B", "AB"],
  },
  {
    id: "5",
    name: "CFC Moto Start",
    address: "Setor de Oficinas, 10 - Ceilândia, Brasília - DF",
    distance: "5.2km",
    rating: 4.0,
    maxRating: 5,
    type: "Parceira",
    categories: ["A"],
  },
]
